/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5a6cde26-dfd4-4c33-9f54-be67cb3ab3b8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FChwfcfxr",
    "aws_user_pools_web_client_id": "439u7bup9hrk45i9nh9f1fpdqh",
    "oauth": {}
};


export default awsmobile;
