/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eaac7bb0-9584-49b3-a322-cec83cdb769b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LY4LFScSa",
    "aws_user_pools_web_client_id": "5bhs02o144c5dcv9l6p5b1jqeu",
    "oauth": {}
};


export default awsmobile;
