name = "nextjs-hockey"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# worker entrypoint produced by OpenNext
main = ".open-next/worker.js"

[build]
command = "npx @opennextjs/cloudflare@latest build"

# Serve the generated static assets as a site bucket
[site]
bucket = ".open-next/assets"