name = "nextjs-hockey"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @opennextjs/cloudflare@latest build"

[[assets]]
bucket = ".open-next/static"
binding = "ASSETS"